version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: severstal
      POSTGRES_PASSWORD: severstal
      POSTGRES_DB: severstal
    ports:
      - "5432:5432"
    restart: unless-stopped
  severstal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"