spring:
  application:
    name: severstal
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        format_sql: true
  datasource:
    url: jdbc:hsqldb:mem:severstal
    username: sa
    password: severstal
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
logging:
  level:
    root: WARN
    ru.severstal.severstalnotetask: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
server:
  port: 80